on:
  push:
  pull_request:

jobs:
  test:
    name: python test
    runs-on : ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: install pytest
        run : pip install -U pytest
        
      - name: run test
        run : pytest -q 
        
