on:
  push:
  pull_request:

jobs:
  test:
    name: python test
    runs-on : ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install pytest
        run: pip install -U pytest

#       - name: Run pytest
#         run: pytest >> README.md

      - run: echo "hello" >> README.md
      
      - name: Commit changes
        run: git config --global user.email "action@github.com"

      - run: git config --global user.name "GitHub Actions"
      -  run:  git add README.md
      -  run:  git commit -m "update README.md with results"
      -  run:  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git push
       
