on:
  push:
  pull_request:

jobs:
  test:
    name: python test
    runs-on : ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: install pytest
        run : pip install -U pytest
        
      - name: write to file
        run : echo "hello" >> text.txt
      

      - name: run test
        run : pytest -q >> README.md
        
      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"
          git add text.txt
          git commit -m "added text file"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
